### PR TITLE
Data file for SiStripApproximateClusterCollection unit test

### PR DESCRIPTION
**Pull request by wddgit**
Add initial data file for SiStripApproximateClusterCollection unit test.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

I don't think this test will actually do anything, but run it to get the box checked. This PR needs to be merged before the cms-sw/cmssw#42859 and the fact that the tests for that PR passed is what is important.

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

tests were done via https://github.com/cms-sw/cmssw/pull/42859

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
